title: "Joaquin Fernandez Tapia"
description: "Personal notes"
url: "https://joakft.github.io"
baseurl: ""          # must be empty for user sites

theme: minima        # built-in GitHub Pages theme
plugins:
  - jekyll-feed
  
# <repo structure>/
# ├─ _config.yml          # site title, theme, (optional) url/baseurl
# ├─ index.md             # homepage (your landing page)
# ├─ posts.md             # simple list of posts (optional page)
# ├─ _posts/              # blog posts: YYYY-MM-DD-title.md
# ├─ assets/
# │  ├─ img/              # images used in posts/pages
# │  └─ css/              # optional custom CSS
# └─ .gitignore           # ignore /_site when building locally