project:
  type: website

website:
  title: "Your Name"
  site-url: https://joakft.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/yourusername
      - icon: linkedin
        href: https://linkedin.com/in/yourusername

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    highlight-style: github
